import React from "react";
import './Sites.css';
import BackButton from "./BackButton.js";
import { Link } from "react-router-dom";


export default class Datenschutzerklärung extends React.Component {
	componentDidMount() {}
		
	render() {
		return(
		<div className="site_container">
            <div className="site_container_content">
                <Link to="/"><BackButton /></Link>
            
            <h1>Datenschutzerklärung</h1>

            
    
            <p>Wir informieren Sie nachfolgend gem&auml;&szlig; den gesetzlichen Vorgaben des Datenschutzrechts (insb. gem&auml;&szlig; BDSG n.F. und der europ&auml;ischen Datenschutz-Grundverordnung &sbquo;DS-GVO&lsquo;) &uuml;ber die Art, den Umfang und Zweck der Verarbeitung personenbezogener Daten durch unser Unternehmen.&nbsp;Diese Datenschutzerkl&auml;rung gilt auch f&uuml;r unsere Websites und Sozial-Media-Profile. Bez&uuml;glich der Definition von Begriffen wie etwa &bdquo;personenbezogene Daten&ldquo; oder &bdquo;Verarbeitung&ldquo; verweisen wir auf Art. 4 DS-GVO.</p>
<p><strong>Name und Kontaktdaten des / der Verantwortlichen</strong><br /> Unser/e Verantwortliche/r (nachfolgend &bdquo;Verantwortlicher&ldquo;) i.S.d. Art. 4 Zif. 7 DS-GVO ist:<br /> <br /> Martin Zimmer Design<br /> Knotterkamp 12<br /> 21335, L&uuml;neburg, Deutschland<br /> Gesch&auml;ftsf&uuml;hrer Martin Zimmer<br /> E-Mail-Adresse: m.zimmer.business@gmail.com<br /> <br /> <strong>Datenarten, Zwecke der Verarbeitung und Kategorien betroffener Personen</strong><br /> </p>
<p>Nachfolgend informieren wir Sie &uuml;ber Art, Umfang und Zweck der Erhebung, Verarbeitung und Nutzung personenbezogener Daten.</p>
<ol>
<li><strong> Arten der Daten, die wir verarbeiten</strong><br /> Nutzungsdaten (Zugriffszeiten, besuchte Websites etc.), Kontaktdaten (Telefonnummer, E-Mail, Fax etc.), Inhaltsdaten (Texteingaben, Videos, Fotos etc.), Kommunikationsdaten (IP-Adresse etc.),&nbsp;<br /> <br /> <strong>2. Zwecke der Verarbeitung nach Art. 13 Abs. 1 c) DS-GVO</strong><br /> Website technisch und wirtschaftlich optimieren, Optimierung und statistische Auswertung unserer Dienste, Nutzererfahrung verbessern, Website benutzerfreundlich gestalten, Erstellung von Statistiken,Vermeidung von SPAM und Missbrauch, Kontaktanfragen abwickeln, Unterbrechungsfreier,sicherer Betrieb unserer Website,&nbsp;<br /> <br /> <strong>3. Kategorien der betroffenen Personen nach Art. 13 Abs. 1 e) DS-GVO</strong><br /> Besucher/Nutzer der Website, Kunden, Interessenten,&nbsp;<br /> <br /> </li>
</ol>
<p>Die betroffenen Personen werden zusammenfassend als &bdquo;Nutzer&ldquo; bezeichnet.</p>
<p><br /> <strong>Rechtsgrundlagen der Verarbeitung personenbezogener Daten</strong></p>
<p>Nachfolgend Informieren wir Sie &uuml;ber die Rechtsgrundlagen der Verarbeitung personenbezogener Daten:</p>
<ol>
<li>Wenn wir Ihre Einwilligung f&uuml;r die Verarbeitung personenbezogenen Daten eingeholt haben, ist Art. 6 Abs. 1 S. 1 lit. a) DS-GVO Rechtsgrundlage.</li>
<li>Ist die Verarbeitung zur Erf&uuml;llung eines Vertrags oder zur Durchf&uuml;hrung vorvertraglicher Ma&szlig;nahmen erforderlich, die auf Ihre Anfrage hin erfolgen, so ist Art. 6 Abs. 1 S. 1 lit. b) DS-GVO Rechtsgrundlage.</li>
<li>Ist die Verarbeitung zur Erf&uuml;llung einer rechtlichen Verpflichtung erforderlich, der wir unterliegen (z.B. gesetzliche Aufbewahrungspflichten), so ist Art. 6 Abs. 1 S. 1 lit. c) DS-GVO Rechtsgrundlage.</li>
<li>Ist die Verarbeitung erforderlich, um lebenswichtige Interessen der betroffenen Person oder einer anderen nat&uuml;rlichen Person zu sch&uuml;tzen, so ist Art. 6 Abs. 1 S. 1 lit. d) DS-GVO Rechtsgrundlage.</li>
<li>Ist die Verarbeitung zur Wahrung unserer oder der berechtigten Interessen eines Dritten erforderlich und &uuml;berwiegen diesbez&uuml;glich Ihre Interessen oder Grundrechte und Grundfreiheiten nicht, so ist Art. 6 Abs. 1 S. 1 lit. f) DS-GVO Rechtsgrundlage.</li>
</ol>
<p><br /> <strong>Weitergabe personenbezogener Daten an Dritte und Auftragsverarbeiter</strong></p>
<p>Ohne Ihre Einwilligung geben wir grunds&auml;tzlich keine Daten an Dritte weiter. Sollte dies doch der Fall sein, dann erfolgt die Weitergabe auf der Grundlage der zuvor genannten Rechtsgrundlagen z.B. bei der Weitergabe von Daten an Online-Paymentanbieter zur Vertragserf&uuml;llung oder aufgrund gerichtlicher Anordnung oder wegen einer gesetzlichen Verpflichtung zur Herausgabe der Daten zum Zwecke der Strafverfolgung, zur Gefahrenabwehr oder zur Durchsetzung der Rechte am geistigen Eigentum.<br /> Wir setzen zudem Auftragsverarbeiter (externe Dienstleister z.B. zum Webhosting unserer Websites und Datenbanken) zur Verarbeitung Ihrer Daten ein. Wenn im Rahmen einer Vereinbarung zur Auftragsverarbeitung an die Auftragsverarbeiter Daten weitergegeben werden, erfolgt dies immer nach Art. 28 DS-GVO. Wir w&auml;hlen dabei unsere Auftragsverarbeiter sorgf&auml;ltig aus, kontrollieren diese regelm&auml;&szlig;ig und haben uns ein Weisungsrecht hinsichtlich der Daten einr&auml;umen lassen. Zudem m&uuml;ssen die Auftragsverarbeiter geeignete technische und organisatorische Ma&szlig;nahmen getroffen haben und die Datenschutzvorschriften gem. BDSG n.F. und DS-GVO einhalten</p>
<p><br /> <strong>Daten&uuml;bermittlung in Drittstaaten</strong></p>
<p>Durch die Verabschiedung der europ&auml;ischen Datenschutz-Grundverordnung (DS-GVO) wurde eine einheitliche Grundlage f&uuml;r den Datenschutz in Europa geschaffen. Ihre Daten werden daher vorwiegend durch Unternehmen verarbeitet, f&uuml;r die DS-GVO Anwendung findet. Sollte doch die Verarbeitung durch Dienste Dritter au&szlig;erhalb der Europ&auml;ischen Union oder des Europ&auml;ischen Wirtschaftsraums stattfinden, so m&uuml;ssen diese die besonderen Voraussetzungen der Art. 44 ff. DS-GVO erf&uuml;llen. Das bedeutet, die Verarbeitung erfolgt aufgrund besonderer Garantien, wie etwa die von der EU-Kommission offiziell anerkannte Feststellung eines der EU entsprechenden Datenschutzniveaus oder der Beachtung offiziell anerkannter spezieller vertraglicher Verpflichtungen, der so genannten &bdquo;Standardvertragsklauseln&ldquo;. Bei US-Unternehmen erf&uuml;llt die Unterwerfung unter das sog. &bdquo;Privacy-Shield&ldquo;, dem Datenschutzabkommen zwischen der EU und den USA, diese Voraussetzungen.</p>
<p><br /> <strong>L&ouml;schung von Daten und Speicherdauer</strong></p>
<p>Sofern nicht in dieser Datenschutzerkl&auml;rung ausdr&uuml;cklich angegeben, werden Ihre personenbezogen Daten gel&ouml;scht oder gesperrt, sobald der Zweck f&uuml;r die Speicherung entf&auml;llt, es sei denn deren weitere Aufbewahrung ist zu Beweiszwecken erforderlich oder dem stehen gesetzliche Aufbewahrungspflichten entgegenstehen. Darunter fallen etwa handelsrechtliche Aufbewahrungspflichten von Gesch&auml;ftsbriefen nach &sect; 257 Abs. 1 HGB (6 Jahre) sowie steuerrechtliche Aufbewahrungspflichten nach &sect; 147 Abs. 1 AO von Belegen (10 Jahre). Wenn die vorgeschriebene Aufbewahrungsfrist abl&auml;uft, erfolgt eine Sperrung oder L&ouml;schung Ihrer Daten, es sei denn die Speicherung ist weiterhin f&uuml;r einen Vertragsabschluss oder zur Vertragserf&uuml;llung erforderlich.</p>
<p><br /> <strong>Bestehen einer automatisierten Entscheidungsfindung</strong></p>
<p>Wir setzen keine automatische Entscheidungsfindung oder ein Profiling ein.</p>
<p><br /> <strong>Bereitstellung unserer Website und Erstellung von Logfiles</strong></p>
<ol>
<li>Wenn Sie unsere Webseite lediglich informatorisch nutzen (also keine Registrierung und auch keine anderweitige &Uuml;bermittlung von Informationen), erheben wir nur die personenbezogenen Daten, die Ihr Browser an unseren Server &uuml;bermittelt. Wenn Sie unsere Website betrachten m&ouml;chten, erheben wir die folgenden Daten:&bull; IP-Adresse;<br /> Internet-Service-Provider des Nutzers;<br /> &bull; Datum und Uhrzeit des Abrufs;<br /> &bull; Browsertyp;<br /> &bull; Sprache und Browser-Version;<br /> &bull; Inhalt des Abrufs;<br /> &bull; Zeitzone;<br /> &bull; Zugriffsstatus/HTTP-Statuscode;<br /> &bull; Datenmenge;<br /> &bull; Websites, von denen die Anforderung kommt;<br /> &bull; Betriebssystem.<br /> Eine Speicherung dieser Daten zusammen mit anderen personenbezogenen Daten von Ihnen findet nicht statt.</li>
<li>Diese Daten dienen dem Zweck der nutzerfreundlichen, funktionsf&auml;higen und sicheren Auslieferung unserer Website an Sie mit Funktionen und Inhalten sowie deren Optimierung und statistischen Auswertung.</li>
<li>Rechtsgrundlage hierf&uuml;r ist unser in den obigen Zwecken auch liegendes berechtigtes Interesse an der Datenverarbeitung nach Art. 6 Abs. 1 S.1 lit. f) DS-GVO.</li>
<li>Wir speichern aus Sicherheitsgr&uuml;nden diese Daten in Server-Logfiles f&uuml;r die Speicherdauer von 60 Tagen. Nach Ablauf dieser Frist werden diese automatisch gel&ouml;scht, es sei denn wir ben&ouml;tigen deren Aufbewahrung zu Beweiszwecken bei Angriffen auf die Serverinfrastruktur oder anderen Rechtsverletzungen.</li>
</ol>
<p><br /> <strong>Cookies</strong></p>
<ol>
<li>Wir verwenden sog. Cookies bei Ihrem Besuch unserer Website. Cookies sind kleine Textdateien, die Ihr Internet-Browser auf Ihrem Rechner ablegt und speichert. Wenn Sie unsere Website erneut aufrufen, geben diese Cookies Informationen ab, um Sie automatisch wiederzuerkennen. Die so erlangten Informationen dienen dem Zweck, unsere Webangebote technisch und wirtschaftlich zu optimieren und Ihnen einen leichteren und sicheren Zugang auf unsere Website zu erm&ouml;glichen. Wir informieren Sie dazu beim Aufruf unserer Website mittels eines Hinweises auf unsere Datenschutzerkl&auml;rung &uuml;ber die Verwendung von Cookies zu den zuvor genannten Zwecken und wie Sie dieser widersprechen bzw. deren Speicherung verhindern k&ouml;nnen (&bdquo;Opt-out&ldquo;). Unsere Website nutzt Session-Cookies, persistente Cookies und Cookies von Drittanbietern:<br /> <br /> <strong> Session-Cookies:</strong>Wir verwenden sog. Cookies zum Wiedererkennen mehrfacher Nutzung eines Angebots durch denselben Nutzer (z.B. wenn Sie sich eingeloggt haben zur Feststellung Ihres Login-Status). Wenn Sie unsere Seite erneut aufrufen, geben diese Cookies Informationen ab, um Sie automatisch wiederzuerkennen. Die so erlangten Informationen dienen dazu, unsere Angebote zu optimieren und Ihnen einen leichteren Zugang auf unsere Seite zu erm&ouml;glichen. Wenn Sie den Browser schlie&szlig;en oder Sie sich ausloggen, werden die Session-Cookies gel&ouml;scht.<br /> <br /> <strong>&bull; Persistente Cookies:</strong>&nbsp;Diese werden automatisiert nach einer vorgegebenen Dauer gel&ouml;scht, die sich je nach Cookie unterscheiden kann. In den Sicherheitseinstellungen Ihres Browsers k&ouml;nnen Sie die Cookies jederzeit l&ouml;schen.<br /> <br /> <strong>&bull; Cookies von Drittanbietern (Third-Party-Cookies):</strong>&nbsp;Entsprechend Ihren W&uuml;nschen k&ouml;nnen Sie k&ouml;nnen Ihre Browser-Einstellung konfigurieren und z. B. Die Annahme von Third-Party-Cookies oder allen Cookies ablehnen. Wir weisen Sie jedoch an dieser Stelle darauf hin, dass Sie dann eventuell nicht alle Funktionen dieser Website nutzen k&ouml;nnen. Lesen Sie N&auml;heres zu diesen Cookies bei den jeweiligen Datenschutzerkl&auml;rungen zu den Drittanbietern.</li>
<li>Rechtsgrundlage dieser Verarbeitung ist Art. 6 Abs. 1 S. lit. b) DS-GVO, wenn die Cookies zur Vertragsanbahnung z.B. bei Bestellungen gesetzt werden und ansonsten haben wir ein berechtigtes Interesse an der effektiven Funktionalit&auml;t der Website, so dass in dem Falle Art. 6 Abs. 1 S. 1 lit. f) DS-GVO Rechtsgrundlage ist.</li>
<li><strong>Widerspruch und &bdquo;Opt-Out&ldquo;:</strong>Das Speichern von Cookies auf Ihrer Festplatte k&ouml;nnen Sie allgemein verhindern, indem Sie in Ihren Browser-Einstellungen &bdquo;keine Cookies akzeptieren&ldquo; w&auml;hlen. Dies kann aber eine Funktionseinschr&auml;nkung unserer Angebote zur Folge haben. Sie k&ouml;nnen dem Einsatz von Cookies von Drittanbietern zu Werbezwecken &uuml;ber ein sog. &bdquo;Opt-out&ldquo; &uuml;ber diese amerikanische Website&nbsp;(https://optout.aboutads.info)&nbsp;oder diese europ&auml;ische Website&nbsp;(www.youronlinechoices.com/de/praferenzmanagement/) widersprechen.</li>
</ol>
<p><br /> <strong>Kontaktaufnahme per Kontaktformular / E-Mail / Fax / Post</strong></p>
<ol>
<li>Bei der Kontaktaufnahme mit uns per Kontaktformular, Fax, Post oder E-Mail werden Ihre Angaben zum Zwecke der Abwicklung der Kontaktanfrage verarbeitet.</li>
<li>Rechtsgrundlage f&uuml;r die Verarbeitung der Daten ist bei Vorliegen einer Einwilligung von Ihnen Art.&nbsp;6 Abs.&nbsp;1 S. 1 lit.&nbsp;a) DS-GVO. Rechtsgrundlage f&uuml;r die Verarbeitung der Daten, die im Zuge einer Kontaktanfrage oder E-Mail, eines Briefes oder Faxes &uuml;bermittelt werden, ist Art.&nbsp;6 Abs.&nbsp;1 S. 1 lit.&nbsp;f) DS-GVO. Der Verantwortliche hat ein berechtigtes Interesse an der Verarbeitung und Speicherung der Daten, um Anfragen der Nutzer beantworten zu k&ouml;nnen, zur Beweissicherung aus Haftungsgr&uuml;nden und um ggf. seiner gesetzlichen Aufbewahrungspflichten bei Gesch&auml;ftsbriefen nachkommen zu k&ouml;nnen. Zielt der Kontakt auf den Abschluss eines Vertrages ab, so ist zus&auml;tzliche Rechtsgrundlage f&uuml;r die Verarbeitung Art.&nbsp;6 Abs.&nbsp;1 S. 1 lit.&nbsp;b) DS-GVO.</li>
<li>Wir k&ouml;nnen Ihre Angaben und Kontaktanfrage in unserem Customer-Relationship-Management System ("CRM System") oder einem vergleichbaren System speichern.</li>
<li>Die Daten werden gel&ouml;scht, sobald sie f&uuml;r die Erreichung des Zweckes ihrer Erhebung nicht mehr erforderlich sind. F&uuml;r die personenbezogenen Daten aus der Eingabemaske des Kontaktformulars und diejenigen, die per E-Mail &uuml;bersandt wurden, ist dies dann der Fall, wenn die jeweilige Konversation mit Ihnen beendet ist. Beendet ist die Konversation dann, wenn sich aus den Umst&auml;nden entnehmen l&auml;sst, dass der betroffene Sachverhalt abschlie&szlig;end gekl&auml;rt ist. Anfragen von Nutzern, die &uuml;ber einen Account bzw. Vertrag mit uns verf&uuml;gen, speichern wir bis zum Ablauf von zwei Jahren nach Vertragsbeendigung. Im Fall von gesetzlichen Archivierungspflichten erfolgt die L&ouml;schung nach deren Ablauf: Ende handelsrechtlicher (6 Jahre) und steuerrechtlicher (10 Jahre) Aufbewahrungspflicht.</li>
<li>Sie haben jederzeit die M&ouml;glichkeit, die Einwilligung nach Art. 6 Abs. 1 S. 1 lit. a) DS-GVO zur Verarbeitung der personenbezogenen Daten zu widerrufen. Nehmen Sie per E-Mail Kontakt mit uns auf, so k&ouml;nnen Sie der Speicherung der personenbezogenen Daten jederzeit widersprechen.</li>
</ol>
<p><br /> <strong>Google Analytics</strong></p>
<ol>
<li>Wir haben das Webseitenanalyse-Tool &bdquo;Google Analytics&ldquo; (Google Ireland Limited, Registernr.: 368047, Gordon House, Barrow Street, Dublin 4, Irland) auf unserer Website integriert.</li>
<li>Beim Besuch unserer Website setzt Google einen Cookie auf Ihren Computer, um die Benutzung unserer Website durch Sie analysieren zu k&ouml;nnen. Die gewonnenen Daten werden in die USA &uuml;bertragen und dort gespeichert. Falls personenbezogen Daten in die USA &uuml;bertragen werden sollten, bietet die Zertifizierung Googles gem&auml;&szlig; Privacy-Shield-Abkommen (www.privacyshield.gov/EU-US-Framework) die Garantie daf&uuml;r, dass das europ&auml;ische Datenschutzrecht eingehalten wird.</li>
<li>Wir haben die IP-Anonymisierung &bdquo;anonymizeIP&ldquo; aktiviert, wodurch die IP-Adressen nur gek&uuml;rzt weiterverarbeitet werden. Auf dieser Webseite wird Ihre IP-Adresse von Google daher innerhalb von Mitgliedstaaten der Europ&auml;ischen Union oder in anderen Vertragsstaaten des Abkommens &uuml;ber den Europ&auml;ischen Wirtschaftsraum zuvor gek&uuml;rzt. Nur in Ausnahmef&auml;llen wird die volle IP-Adresse an einen Server von Google in den USA &uuml;bertragen und dort gek&uuml;rzt. Im Auftrag des Betreibers dieser Webseite wird Google diese Informationen benutzen, um Ihre Nutzung der Webseite auszuwerten, um Reports &uuml;ber die Webseitenaktivit&auml;ten zusammenzustellen und um weitere, mit der Websitenutzung und der Internetnutzung verbundene, Dienstleistungen gegen&uuml;ber dem Verantwortlichen zu erbringen. Wir haben dar&uuml;ber hinaus die ger&auml;te&uuml;bergreifende Analyse von Website-Besuchern aktiviert, die &uuml;ber eine sog. User-ID durchgef&uuml;hrt wird. Die im Rahmen von Google Analytics von Ihrem Browser &uuml;bermittelte IP-Adresse wird nicht mit anderen Daten von Google zusammengef&uuml;hrt. Die Nutzung von Google Analytics dient dem Zweck der Analyse, Optimierung und Verbesserung unserer Website.</li>
<li>Rechtsgrundlage hierf&uuml;r ist unser in den obigen Zwecken auch liegendes berechtigtes Interesse an der Datenverarbeitung nach Art. 6 Abs. 1 S.1 lit. f) DS-GVO.</li>
<li>Die von uns gesendeten und mit Cookies, Nutzerkennungen (z. B. User-ID) oder Werbe-IDs verkn&uuml;pften Daten werden nach 24 Monaten automatisch gel&ouml;scht. Die L&ouml;schung von Daten, deren Aufbewahrungsdauer erreicht ist, erfolgt automatisch einmal im Monat.</li>
<li>Weitere Informationen zu Datennutzung bei Google Analytics finden Sie hier:&nbsp;www.google.com/analytics/terms/de.html(Nutzungsbedingungen von Analytics),&nbsp;support.google.com/analytics/answer/6004245?hl=de&nbsp;(Hinweise zum Datenschutz bei Analytics) und Googles Datenschutzerkl&auml;rung&nbsp;policies.google.com/privacy.</li>
<li>Widerspruch und &bdquo;Opt-Out&ldquo;: Das Speichern von Cookies auf Ihrer Festplatte k&ouml;nnen Sie allgemein verhindern, indem Sie in Ihren Browser-Einstellungen &bdquo;keine Cookies akzeptieren&ldquo; w&auml;hlen. Dies kann aber eine Funktionseinschr&auml;nkung unserer Angebote zur Folge haben. Sie k&ouml;nnen dar&uuml;ber hinaus die Erfassung der, durch das Cookie erzeugten und auf Ihre Nutzung der Website bezogenen, Daten an Google sowie die Verarbeitung dieser Daten durch Google verhindern, indem sie das unter dem folgenden Link verf&uuml;gbare Browser-Plugin herunterladen und installieren:&nbsp;tools.google.com/dlpage/gaoptout?hl=de</li>
<li>Als Alternative zum obigen Browser-Plugin k&ouml;nnen Sie die Erfassung durch Google Analytics unterbinden, indem Sie&nbsp;<strong>[__hier bitte__den Analytics Opt-Out Link Ihrer Webseite einf&uuml;gen]</strong> Durch den Klick wird ein &bdquo;Opt-out&ldquo;-Cookie gesetzt, das die Erfassung Ihrer Daten beim Besuch dieser Webseite zuk&uuml;nftig verhindert. Dieses Cookie gilt nur f&uuml;r unsere Webseite und Ihren aktuellen Browser und hat nur solange Bestand bis Sie Ihre Cookies l&ouml;schen. In dem Falle m&uuml;ssten Sie das Cookie erneut setzen.</li>
<li>Die ger&auml;te&uuml;bergreifende Nutzeranalyse k&ouml;nnen Sie in Ihrem Google-Account unter &bdquo;Meine Daten &gt; pers&ouml;nliche Daten&ldquo; deaktivieren.</li>
</ol>
<p><br /> <strong>YouTube-Videos</strong></p>
<ol>
<li>Wir haben auf unserer Website YouTube-Videos von youtube.com mittels der embedded-Funktion eingebunden, so dass diese auf unserer Website direkt aufrufbar sind. YouTube geh&ouml;rt zur Google Ireland Limited, Registernr.: 368047, Gordon House, Barrow Street, Dublin 4, Irland. Wir haben die Videos im sog. &bdquo;erweiterten Datenschutz-Modus&ldquo; eingebunden, ohne dass mit Cookies das Nutzungsverhalten erfasst wird, um die Videowiedergabe zu personalisieren. Stattdessen basieren die Videoempfehlungen auf dem aktuell abgespielten Video. Videos, die im erweiterten Datenschutzmodus in einem eingebetteten Player wiedergegeben werden, wirken sich nicht darauf aus, welche Videos Ihnen auf YouTube empfohlen werden.Beim Start eines Videos (Klick aufs Video) erh&auml;lt YouTube die Information, dass Sie die entsprechende Unterseite unserer Website aufgerufen haben. Die gewonnenen Daten werden in die USA &uuml;bertragen und dort gespeichert. Dies erfolgt auch ohne Nutzerkonto bei Google. Sollten Sie in Ihren Google-Account eingeloggt sein, kann Google die obigen Daten Ihrem Account zuordnen. Wenn Sie dies nicht w&uuml;nschen, m&uuml;ssen Sie sich in Ihrem Google-Account ausloggen. Google erstellt aus solchen Daten Nutzerprofile und nutzt diese Daten zum Zwecke der Werbung, Marktforschung oder Optimierung seiner Websites.</li>
<li>Rechtsgrundlage hierf&uuml;r ist unser in den obigen Zwecken auch liegendes berechtigtes Interesse an der Datenverarbeitung nach Art. 6 Abs. 1 S.1 lit. f) DS-GVO.</li>
<li>Sie haben gegen&uuml;ber Google ein Widerspruchsrecht gegen die Bildung von Nutzerprofilen. Bitte richten Sie sich deswegen direkt an Google &uuml;ber die unten genannte Datenschutzerkl&auml;rung. Ein Opt-Out-Widerspruch hinsichtlich der Werbe-Cookies k&ouml;nnen Sie hier in Ihrem Google-Account vornehmen:<br /> adssettings.google.com/authenticated.</li>
<li>In den Nutzungsbedingungen von YouTube unter&nbsp;youtube.com/t/termsund in der Datenschutzerkl&auml;rung f&uuml;r Werbung von Google unter&nbsp;policies.google.com/technologies/ads&nbsp;finden Sie weitere Informationen zur Verwendung von Google Cookies und deren Werbetechnologien, Speicherdauer, Anonymisierung, Standortdaten, Funktionsweise und Ihre Rechte. Allgemeine Datenschutzerkl&auml;rung von Google:&nbsp;policies.google.com/privacy.</li>
<li>Google ist nach dem EU-US Privacy Shield zertifiziert (www.privacyshield.gov/EU-US-Framework) und daher verpflichtet europ&auml;isches Datenschutzrecht einzuhalten.</li>
</ol>
<p><br /> <strong>Google ReCAPTCHA</strong></p>
<ol>
<li>Wir haben auf unserer Webseite die Anti-Spam-Funktion &bdquo;reCAPTCHA&ldquo; von &bdquo;Google&ldquo; (Google Ireland Limited, Registernr.: 368047, Gordon House, Barrow Street, Dublin 4, Irland) integriert. Durch den Einsatz von &bdquo;reCAPTCHA&ldquo; in unseren Formularen k&ouml;nnen wir feststellen, ob die Eingabe durch eine Maschine (Robot) oder einen Menschen erfolgte. Bei der Nutzung des Dienstes k&ouml;nnen Ihre IP-Adresse und ggf. weitere daf&uuml;r ben&ouml;tigte Daten an Google-Server in den USA &uuml;bertragen werden.</li>
<li>Zweck der Verarbeitung dieser Daten ist die Vermeidung von Spam und Missbrauch sowie unser wirtschaftliches Interesse an der Optimierung unserer Website.</li>
<li>Rechtsgrundlage hierf&uuml;r ist unser in den obigen Zwecken auch liegendes berechtigtes Interesse an der Datenverarbeitung nach Art. 6 Abs. 1 S.1 lit. f) DS-GVO.</li>
<li>Google ist unter dem Privacy-Shield-Abkommen zertifiziert (www.privacyshield.gov/EU-US-Framework). So wird sichergestellt, dass das europ&auml;ische Datenschutzrecht eingehalten wird.</li>
<li>Weitere Informationen finden Sie zu Google ReCAPTCHA unter&nbsp;www.google.com/recaptcha/sowie in der Datenschutzerkl&auml;rung von Google unter:&nbsp;policies.google.com/privacy.</li>
</ol>
<p><br /> <strong>Google Maps</strong></p>
<ol>
<li>Wir haben auf unserer Website Karten von &bdquo;Google Maps&ldquo; (Google Ireland Limited, Registernr.: 368047, Gordon House, Barrow Street, Dublin 4, Irland) integriert. Damit k&ouml;nnen wirden Standort von Adressen und eine Anfahrtsbeschreibung direkt auf unserer Website in interaktiven Karten anzeigen und Ihnen die Nutzung dieses Tools erm&ouml;glichen.</li>
<li>Bei dem Abruf unserer Website, wo Google Maps integriert ist, wird eine Verbindung zu den Servern von Google in den USA aufgebaut. Hierbei k&ouml;nnen Ihre IP und Standort an Google &uuml;bertragen werden. Zudem erh&auml;lt Google die Information, dass Sie die entsprechende Seite aufgerufen haben. Dies erfolgt auch ohne Nutzerkonto bei Google. Sollten Sie in Ihren Google-Account eingeloggt sein, kann Google die obigen Daten Ihrem Account zuordnen. Wenn Sie dies nicht w&uuml;nschen, m&uuml;ssen Sie sich bei Ihrem Google-Account ausloggen. Google erstellt aus solchen Daten Nutzerprofile und nutzt diese Daten zum Zwecke der Werbung, Marktforschung oder Optimierung seiner Websites.</li>
<li>Rechtsgrundlage hierf&uuml;r ist unser in den obigen Zwecken auch liegendes berechtigtes Interesse an der Datenverarbeitung nach Art. 6 Abs. 1 S.1 lit. f) DS-GVO.</li>
<li>Sie haben gegen&uuml;ber Google ein Widerspruchsrecht gegen die Bildung von Nutzerprofilen. Bitte richten Sie sich deswegen direkt an Google &uuml;ber die unten genannte Datenschutzerkl&auml;rung. Ein Opt-Out-Widerspruch hinsichtlich der Werbe-Cookies k&ouml;nnen Sie hier in Ihrem Google-Account vornehmen:<br /> adssettings.google.com/authenticated.</li>
<li>In den Nutzungsbedingungen von Google Maps unter&nbsp;www.google.com/intl/de_de/help/terms_maps.htmlund in der Datenschutzerkl&auml;rung f&uuml;r Werbung von Google unter&nbsp;policies.google.com/technologies/ads&nbsp;finden Sie weitere Informationen zur Verwendung von Google Cookies und deren Werbetechnologien, Speicherdauer, Anonymisierung, Standortdaten, Funktionsweise und Ihre Rechte. Allgemeine Datenschutzerkl&auml;rung von Google:&nbsp;policies.google.com/privacy.</li>
<li>Google ist nach dem EU-US Privacy Shield zertifiziert (www.privacyshield.gov/EU-US-Framework) und daher verpflichtet europ&auml;isches Datenschutzrecht einzuhalten.</li>
</ol>
<p><br /> <strong>Pr&auml;senz in sozialen Medien</strong></p>
<ol>
<li>Wir unterhalten in sozialen Medien Profile bzw. Fanpages, um mit den dort angeschlossenen und registrierten Nutzern zu kommunizieren und um &uuml;ber unsere Produkte, Angebote und Dienstleistungen zu informieren. Die US-Anbieter sind nach dem sog. Privacy-Shield zertifiziert und damit verpflichtet europ&auml;ischen Datenschutz einzuhalten. Bei der Nutzung und dem Aufruf unseres Profils im jeweiligen Netzwerk durch Sie gelten die jeweiligen Datenschutzhinweise und Nutzungsbedingungen des jeweiligen Netzwerks.</li>
<li>Wir verarbeiten Ihre Daten, die Sie uns &uuml;ber diese Netzwerke senden, um mit Ihnen zu kommunizieren und um Ihre dortigen Nachrichten zu beantworten.</li>
<li>Die Rechtsgrundlage f&uuml;r die Verarbeitung der personenbezogenen Daten ist unser berechtigtes Interesse an der Kommunikation mit den Nutzern und unsere Au&szlig;endarstellung zwecks Werbung gem&auml;&szlig; Art. 6 Abs. 1 S. 1 lit. f) DS-GVO. Soweit Sie dem Verantwortlichen des sozialen Netzwerks eine Einwilligung in die Verarbeitung Ihrer personenbezogenen Daten erteilt haben, ist Rechtsgrundlage Art. 6 Abs. 1 S. 1 lit. a) und Art. 7 DS-GVO.</li>
<li>Die Datenschutzhinweise, Auskunftsm&ouml;glichkeiten und Widerspruchm&ouml;glichkeiten (Opt-Out) der jeweiligen Netzwerke finden Sie hier:<br /> <br /><strong>Instagram</strong>&nbsp;(Instagram Inc., 1601 Willow Road, Menlo Park, CA, 94025, USA) &ndash; Datenschutzerkl&auml;rung/ Opt-Out:&nbsp;instagram.com/about/legal/privacy/.<br /> <br /> &bull;&nbsp;<strong>Twitter</strong>&nbsp;(Twitter Inc., 1355 Market Street, Suite 900, San Francisco, CA 94103, USA) - Datenschutzerkl&auml;rung:&nbsp;https://twitter.com/de/privacy, Opt-Out:&nbsp;twitter.com/personalization, Privacy Shield:&nbsp;www.privacyshield.gov/participant?id=a2zt0000000TORzAAO&amp;status=Active.</li>
</ol>
<p><br /> <strong>Social-Media-Plug-ins</strong></p>
<ol>
<li>Wir setzen auf unserer Webseite Social-Media-Plug-ins von sozialen Netzwerken ein. Dabei nutzen wir die sog.&nbsp;<strong>&bdquo;Zwei-Klick-L&ouml;sung&ldquo;-Shariff</strong>von c&rsquo;t bzw. heise.de. Beim Abruf unserer Website werden dadurch&nbsp;<strong>keine personenbezogenen Daten</strong>&nbsp;an die Anbieter der Plug-ins &uuml;bermittelt. Neben dem Logo bzw. der Marke des sozialen Netzwerks finden Sie einen Regler, mit dem Sie das Plug-in per Klick aktivieren k&ouml;nnen. Nach der Aktivierung erh&auml;lt der Anbieter des sozialen Netzwerks die Information, dass Sie unsere Website aufgerufen haben und Ihre personenbezogenen Daten an den Anbieter des Plug-ins &uuml;bermittelt und dort gespeichert werden. Hierbei handelt es sich um sog. Thirdparty Cookies. Bei einigen Anbietern wie Facebook und XING wird nach deren Angaben Ihre IP nach der Erhebung sofort anonymisiert.</li>
<li>Die &uuml;ber den Nutzer erhobenen Daten speichert der Plug-in-Anbieter als Nutzungsprofile. Diese werden f&uuml;r Zwecke der Werbung, Marktforschung und/oder bedarfsgerechten Gestaltung seiner Website verwendet. Eine solche Auswertung erfolgt insbesondere (auch f&uuml;r nicht eingeloggte Nutzer) zur Darstellung von bedarfsgerechter Werbung und um andere Nutzer des sozialen Netzwerks &uuml;ber die Aktivit&auml;ten des Nutzers auf unserer Website zu informieren. Dem Nutzer steht ein Widerspruchsrecht gegen die Bildung dieser Nutzerprofile zu, wobei man sich zur Aus&uuml;bung dieses Rechts an den jeweiligen Plug-in-Anbieter wenden muss.</li>
<li>Rechtsgrundlage f&uuml;r die Nutzung der Plug-ins ist unser berechtigtes Interesse an der Verbesserung und Optimierung unserer Website durch die Steigerung unserer Bekanntheit mittels sozialer Netzwerke sowie die M&ouml;glichkeit der Interaktion mit Ihnen und der Nutzer untereinander &uuml;ber soziale Netzwerke gem&auml;&szlig; Art. 6 Abs. 1 S.1 lit. f) DS-GVO.</li>
<li>Auf die erhobenen Daten und Datenverarbeitungsvorg&auml;nge haben wir keinen Einfluss. Auch haben wir keine Kenntnis vom Umfang der Datenerhebung, vom Zweck der Verarbeitung und von den Speicherfristen. Auch zur L&ouml;schung der erhobenen Daten durch den Plug-in-Anbieter liegen uns keine Informationen vor.</li>
<li>Wir verweisen hinsichtlich des Zwecks und Umfangs der Datenerhebung und Verarbeitung auf die jeweiligen Datenschutzerkl&auml;rungen der sozialen Netzwerke. Zudem finden Sie dort auch Hinweise zu Ihren Rechten und Einstellungsm&ouml;glichkeiten zum Schutz Ihrer personenbezogenen Daten.</li>
</ol>
<p><strong>Twitter</strong></p>
<ol>
<li>Wir haben auf unserer Website Plug-Ins des sozialen Netzwerks Twitter.com (Twitter Inc., 1355 Market St., Suite 900, San Francisco, California 94103, USA) im Rahmen der sog. &bdquo;Zwei-Klick-L&ouml;sung&ldquo; von Shariff integriert. Diese Plug-Ins erkennen Sie an dem Twitter-Logo mit wei&szlig;em Vogel auf blauem Hintergrund. Eine &Uuml;bersicht &uuml;ber Twitter-Buttons bzw. Tweets finden Sie unter:&nbsp;developer.twitter.com/en/docs/twitter-for-websites/overview.</li>
<li>Wenn Sie in Ihren Twitter-Account eingeloggt sind, w&auml;hrend Sie die Twitter-Plug-ins willentlich aktivieren, kann Twitter den Anruf unserer Website Ihrem Twitter-Profil zuordnen. Welche Daten an Twitter &uuml;bermittelt werden, ist uns nicht bekannt.</li>
<li>Wenn Sie die Daten&uuml;bermittlung bei Aktivierung des Plug-ins an Twitter ausschlie&szlig;en m&ouml;chten, dann loggen Sie sich vor dem Besuch unserer Website bei Twitter aus und l&ouml;schen Ihre Cookies.</li>
<li>Zweck und Umfang der Datenerhebung sowie ihre weitere Verarbeitung und Nutzung der Daten durch Twitter sowie Ihre diesbez&uuml;glichen Rechte und Einstellungsm&ouml;glichkeiten zum Schutz Ihrer Privatsph&auml;re, k&ouml;nnen Sie den Datenschutzhinweisen von Twitter entnehmen:&nbsp;twitter.com/de/privacy. Widerspruch (Opt-Out):&nbsp;twitter.com/personalization.</li>
<li>Twitter hat sich dem Privacy Shield unterworfen und stellt damit sicher, dass europ&auml;isches Datenschutzrecht eingehalten wird:&nbsp;www.privacyshield.gov/EU-US-Framework.</li>
</ol>
<p><strong>Instagram</strong></p>
<ol>
<li>Wir haben auf unserer Website Plug-Ins vom sozialen Netzwerk Instagram (Instagram LLC., 1601 Willow Road, Menlo Park, CA, 94025, USA) im Rahmen der sog. &bdquo;Zwei-Klick-L&ouml;sung&ldquo; von Shariff integriert. Diese erkennen Sie am Instagram-Logo in der Form einer viereckigen Kamera.</li>
<li>Wenn Sie willentlich das Plug-in aktivieren, wird hierbei eine Verbindung von Ihrem Browser zu den Servern von Instagram hergestellt. Dabei erh&auml;lt Instagram die Information, einschlie&szlig;lich Ihrer IP-Adresse, dass Sie unsere Seite besucht haben und &uuml;bertr&auml;gt die Information an Server von Instagram in den USA, wo diese Information gespeichert wird. Wenn Sie bei Instagram in Ihren Account eingeloggt sind, kann Instagram diese Information Ihrem Account zuordnen und Sie k&ouml;nnen den Instagram-Button anklicken und so die Inhalte unserer Seiten auf Ihrem Instagram-Account teilen und speichern sowie ggf. Ihren dortigen Freunden anzeigen. Wir haben keine Kenntnis &uuml;ber den genauen Inhalt der &uuml;bermittelten Daten, deren Nutzung und Speicherdauer durch Instagram.</li>
<li>Wenn Sie sich bei Instagram vor dem Besuch unserer Website ausloggen und Ihre Cookies l&ouml;schen, werden bei der Aktivierung des Plug-ins keine Daten &uuml;ber den Besuch unserer Website Ihrem Profil auf Instagram zugeordnet.</li>
<li>Sie erhalten weitere Informationen in der Datenschutzerkl&auml;rung von Instagram unter&nbsp;help.instagram.com/519522125107875und zu den Einstellungen zum Schutz der Privatsph&auml;re hier:&nbsp;help.instagram.com/196883487377501.</li>
</ol>
<p><br /> <strong>Rechte der betroffenen Person</strong></p>
<ol>
<li><strong>Widerspruch oder Widerruf gegen die Verarbeitung Ihrer Daten<br /> <br /> Soweit die Verarbeitung auf Ihrer Einwilligung gem&auml;&szlig; Art. 6 Abs. 1 S. 1 lit. a), Art. 7 DS-GVO beruht, haben Sie das Recht, die Einwilligung jederzeit zu widerrufen. Die Rechtm&auml;&szlig;igkeit der aufgrund der Einwilligung bis zum Widerruf erfolgten Verarbeitung wird dadurch nicht ber&uuml;hrt.<br /> <br /> Soweit wir die Verarbeitung Ihrer personenbezogenen Daten auf die Interessenabw&auml;gung gem&auml;&szlig; Art. 6 Abs. 1 S. 1 lit. f) DS-GVO st&uuml;tzen, k&ouml;nnen Sie Widerspruch gegen die Verarbeitung einlegen. Dies ist der Fall, wenn die Verarbeitung insbesondere nicht zur Erf&uuml;llung eines Vertrags mit Ihnen erforderlich ist, was von uns jeweils bei der nachfolgenden Beschreibung der Funktionen dargestellt wird. Bei Aus&uuml;bung eines solchen Widerspruchs bitten wir um Darlegung der Gr&uuml;nde, weshalb wir Ihre personenbezogenen Daten nicht wie von uns durchgef&uuml;hrt verarbeiten sollten. Im Falle Ihres begr&uuml;ndeten Widerspruchs pr&uuml;fen wir die Sachlage und werden entweder die Datenverarbeitung einstellen bzw. anpassen oder Ihnen unsere zwingenden schutzw&uuml;rdigen Gr&uuml;nde aufzeigen, aufgrund derer wir die Verarbeitung fortf&uuml;hren.<br /> <br /> Sie k&ouml;nnen der Verarbeitung Ihrer personenbezogenen Daten f&uuml;r Zwecke der Werbung und Datenanalyse jederzeit widersprechen. Das Widerspruchsrecht k&ouml;nnen Sie kostenfrei aus&uuml;ben. &Uuml;ber Ihren Werbewiderspruch k&ouml;nnen Sie uns unter folgenden Kontaktdaten informieren:<br /> <br /> Martin Zimmer Design<br /> Knotterkamp 12<br /> 21335, L&uuml;neburg, Deutschland<br /> Gesch&auml;ftsf&uuml;hrer Martin Zimmer<br /> E-Mail-Adresse: m.zimmer.business@gmail.com</strong></li>
<li><br /><strong>Recht auf Auskunft</strong><br /> Sie haben ein Recht auf Auskunft &uuml;ber Ihre bei uns gespeicherten pers&ouml;nlichen Daten nach Art. 15 DS-GVO. Dies beinhaltet insbesondere die Auskunft &uuml;ber die Verarbeitungszwecke, die Kategorie der personenbezogenen Daten, die Kategorien von Empf&auml;ngern, gegen&uuml;ber denen Ihre Daten offengelegt wurden oder werden, die geplante Speicherdauer, die Herkunft ihrer Daten, sofern diese nicht direkt bei Ihnen erhoben wurden.</li>
<li><strong>Recht auf Berichtigung</strong><br /> Sie haben ein Recht auf Berichtigung unrichtiger oder auf Vervollst&auml;ndigung richtiger Daten nach Art. 16 DS-GVO.</li>
<li><strong>Recht auf L&ouml;schung</strong><br /> Sie haben ein Recht auf L&ouml;schung Ihrer bei uns gespeicherten Daten nach Art. 17 DS-GVO, es sei denn gesetzliche oder vertraglichen Aufbewahrungsfristen oder andere gesetzliche Pflichten bzw. Rechte zur weiteren Speicherung stehen dieser entgegen.</li>
<li><strong>Recht auf Einschr&auml;nkung</strong><br /> Sie haben das Recht, eine Einschr&auml;nkung bei der Verarbeitung Ihrer personenbezogenen Daten zu verlangen, wenn eine der Voraussetzungen in Art. 18 Abs. 1 lit. a) bis d) DS-GVO erf&uuml;llt ist:<br /> Wenn Sie die Richtigkeit der Sie betreffenden personenbezogenen f&uuml;r eine Dauer bestreiten, die es dem Verantwortlichen erm&ouml;glicht, die Richtigkeit der personenbezogenen Daten zu &uuml;berpr&uuml;fen;<br />  &bull; die Verarbeitung unrechtm&auml;&szlig;ig ist und Sie die L&ouml;schung der personenbezogenen Daten ablehnen und stattdessen die Einschr&auml;nkung der Nutzung der personenbezogenen Daten verlangen;<br /> &bull; der Verantwortliche die personenbezogenen Daten f&uuml;r die Zwecke der Verarbeitung nicht l&auml;nger ben&ouml;tigt, Sie diese jedoch zur Geltendmachung, Aus&uuml;bung oder Verteidigung von Rechtsanspr&uuml;chen ben&ouml;tigen, oder<br />  &bull; wenn Sie Widerspruch gegen die Verarbeitung gem&auml;&szlig; Art. 21 Abs. 1 DS-GVO eingelegt haben und noch nicht feststeht, ob die berechtigten Gr&uuml;nde des Verantwortlichen gegen&uuml;ber Ihren Gr&uuml;nden &uuml;berwiegen.</li>
<li><strong>Recht auf Daten&uuml;bertragbarkeit</strong><br /> Sie haben ein Recht auf Daten&uuml;bertragbarkeit nach Art. 20 DS-GVO, was bedeutet, dass Sie die bei uns &uuml;ber Sie gespeicherten personenbezogenen Daten in einem strukturierten, g&auml;ngigen und maschinenlesbaren Format erhalten k&ouml;nnen oder die &Uuml;bermittlung an einen anderen Verantwortlichen verlangen k&ouml;nnen.</li>
<li><strong>Recht auf Beschwerde</strong><br /> Sie haben ein Recht auf Beschwerde bei einer Aufsichtsbeh&ouml;rde. In der Regel k&ouml;nnen Sie sich hierf&uuml;r an die Aufsichtsbeh&ouml;rde insbesondere in dem Mitgliedstaat ihres Aufenthaltsorts, ihres Arbeitsplatzes oder des Orts des mutma&szlig;lichen Versto&szlig;es wenden.</li>
</ol>
<p><br /> <strong>Datensicherheit</strong></p>
<p>Um alle personenbezogen Daten, die an uns &uuml;bermittelt werden, zu sch&uuml;tzen und um sicherzustellen, dass die Datenschutzvorschriften von uns, aber auch unseren externen Dienstleistern eingehalten werden, haben wir geeignete technische und organisatorische Sicherheitsma&szlig;nahmen getroffen. Deshalb werden unter anderem alle Daten zwischen Ihrem Browser und unserem Server &uuml;ber eine sichere SSL-Verbindung verschl&uuml;sselt &uuml;bertragen.</p>
<p><br /> <br /> <strong>Stand: 23.05.2019</strong></p>
<p>Quelle:&nbsp;<a href="https://www.juraforum.de/datenschutzerklaerung-muster/">Muster-Datenschutzerkl&auml;rung von JuraForum.de</a></p>
<p>&nbsp;</p>
            
        </div>
		</div>
		);
		}
	}
